services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: king@786
      MYSQL_DATABASE: shopsphere

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
     
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10 

  shopsphere:
    build:
      context: .

    container_name: shopsphere-app

    depends_on:
      - mysql

    ports:
      - "8080:8080"

volumes:
  mysql-data: